# self_attention.py
import numpy as np

def softmax(x: np.ndarray) -> np.ndarray:
    """Computes softmax values for each row of matrix x (for probability normalization)."""
    # Subtracting the max for numerical stability (prevents overflow)
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

def scaled_dot_product_attention(Q: np.ndarray, K: np.ndarray, V: np.ndarray) -> tuple:
    """
    Computes Scaled Dot-Product Attention from scratch using NumPy.
    Formula: Softmax( (Q * K^T) / sqrt(d_k) ) * V
    """
    # 1. Get dimension of Key vectors (d_k) to scale the dot product
    d_k = K.shape[-1]
    
    # 2. Compute the raw attention scores (MatMul of Q and Transposed K)
    # This represents the raw 'similarity' between each Query and Key
    scores = np.matmul(Q, K.T)
    print(f"\n[Step 1] Raw Attention Scores (Q * K^T):\n{scores}")
    
    # 3. Scale the scores by the square root of d_k
    # This scaling prevents gradients from becoming too small during training
    scaled_scores = scores / np.sqrt(d_k)
    print(f"\n[Step 2] Scaled Scores (divided by sqrt({d_k})): \n{scaled_scores}")
    
    # 4. Apply Softmax to get normalized Attention Weights (probabilities summing to 1.0)
    attention_weights = softmax(scaled_scores)
    print(f"\n[Step 3] Attention Weights (Softmax Probabilities):\n{attention_weights}")
    
    # 5. Multiply weights by Value vectors (V) to get the final context-aware output
    output = np.matmul(attention_weights, V)
    print(f"\n[Step 4] Final Attention Output (Weights * V):\n{output}")
    
    return output, attention_weights

if __name__ == "__main__":
    print("====================================================")
    # Let's simulate a tiny 3-word sentence embedding
    # Words: ["Shipment", "delayed", "Karachi"]
    # Sequence length (seq_len) = 3
    # Embedding dimension (d_k/d_v) = 4 (for simple visualization)
    
    # Simulate Query, Key, and Value matrices (typically generated by linear layers)
    np.random.seed(42)
    Q = np.random.uniform(-1, 1, size=(3, 4))
    K = np.random.uniform(-1, 1, size=(3, 4))
    V = np.random.uniform(0, 10, size=(3, 4))  # Values represent our physical data embeddings
    
    print("Simulated Sentence Tokens: ['Shipment', 'delayed', 'Karachi']")
    print(f"Generated Query Matrix (Q):\n{Q}")
    print(f"Generated Key Matrix (K):\n{K}")
    print(f"Generated Value Matrix (V):\n{V}")
    print("====================================================")
    
    # Execute Attention
    output, weights = scaled_dot_product_attention(Q, K, V)